[workspace]
resolver = "3"
members = ["crates/core", "crates/cli", "crates/app"]

[workspace.package]
version = "0.0.1"
edition = "2024"
license = "GPL-3.0-or-later"
repository = "https://github.com/xevrion/gyotaku"

[workspace.dependencies]
gyotaku-core = { path = "crates/core" }
anyhow = "1.0"
directories = "6.0"

[profile.release]
lto = "thin"
codegen-units = 1
