// Generated by scripts/demo-shots.ts features. Don't edit by hand.
import nearMailImage from "./near-mail.webp";
import nearMailOcr from "./near-mail.json";
import nearOrderImage from "./near-order.webp";
import nearOrderOcr from "./near-order.json";
import nearChatImage from "./near-chat.webp";
import nearChatOcr from "./near-chat.json";
import burst1Image from "./burst-1.webp";
import burst1Ocr from "./burst-1.json";
import burst2Image from "./burst-2.webp";
import burst2Ocr from "./burst-2.json";
import burst3Image from "./burst-3.webp";
import burst3Ocr from "./burst-3.json";
import burst4Image from "./burst-4.webp";
import burst4Ocr from "./burst-4.json";
import bookingImage from "./booking.webp";
import bookingOcr from "./booking.json";
import otp1Image from "./otp-1.webp";
import otp1Ocr from "./otp-1.json";
import otp2Image from "./otp-2.webp";
import otp2Ocr from "./otp-2.json";
import otp3Image from "./otp-3.webp";
import otp3Ocr from "./otp-3.json";
import otp4Image from "./otp-4.webp";
import otp4Ocr from "./otp-4.json";
import copiedImage from "./copied.webp";
import copiedOcr from "./copied.json";
import scriptsImage from "./scripts.webp";
import scriptsOcr from "./scripts.json";

export const SHOTS = {
  nearMail: { ...nearMailOcr, image: nearMailImage },
  nearOrder: { ...nearOrderOcr, image: nearOrderImage },
  nearChat: { ...nearChatOcr, image: nearChatImage },
  burst1: { ...burst1Ocr, image: burst1Image },
  burst2: { ...burst2Ocr, image: burst2Image },
  burst3: { ...burst3Ocr, image: burst3Image },
  burst4: { ...burst4Ocr, image: burst4Image },
  booking: { ...bookingOcr, image: bookingImage },
  otp1: { ...otp1Ocr, image: otp1Image },
  otp2: { ...otp2Ocr, image: otp2Image },
  otp3: { ...otp3Ocr, image: otp3Image },
  otp4: { ...otp4Ocr, image: otp4Image },
  copied: { ...copiedOcr, image: copiedImage },
  scripts: { ...scriptsOcr, image: scriptsImage },
};
