// Generated by scripts/demo-shots.ts. Don't edit by hand.
import img0 from "./invoice.webp";
import ocr0 from "./invoice.json";
import img1 from "./otp.webp";
import ocr1 from "./otp.json";
import img2 from "./terminal.webp";
import ocr2 from "./terminal.json";
import img3 from "./boarding.webp";
import ocr3 from "./boarding.json";
import img4 from "./wifi.webp";
import ocr4 from "./wifi.json";
import img5 from "./sheet.webp";
import ocr5 from "./sheet.json";
import img6 from "./notes.webp";
import ocr6 from "./notes.json";
import img7 from "./map.webp";
import ocr7 from "./map.json";

export const DEMO_SHOTS = [
  { ...ocr0, image: img0 },
  { ...ocr1, image: img1 },
  { ...ocr2, image: img2 },
  { ...ocr3, image: img3 },
  { ...ocr4, image: img4 },
  { ...ocr5, image: img5 },
  { ...ocr6, image: img6 },
  { ...ocr7, image: img7 },
];
